<?php
// +----------------------------------------------------------------------
// | xu: 2021/4/18 0018
// +----------------------------------------------------------------------

namespace x_tp6\providers;

/**
 * 修复 定义了查询事件 就取值
 * Class Db
 *
 * @package x_tp6\providers
 */
class Db extends \think\Db
{

    public function trigger(string $event, $params = null, bool $once = false)
    {
        // 原返回值 是取所有事件的返回值[null, false]
        return parent::trigger($event, $params, true); // TODO: Change the autogenerated stub
    }
}